/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XvJGoAF2hZu
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Popover, PopoverTrigger, PopoverContent } from "@/components/ui/popover"
import { Calendar } from "@/components/ui/calendar"

export function FacilityEdit() {
  return (
    <div className="flex flex-col min-h-screen">
      {/* <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Link href="#" className="flex items-center gap-2" prefetch={false}>
            <Package2Icon className="h-6 w-6" />
            <span className="font-semibold text-lg">유니스포츠</span>
          </Link>
          <nav className="hidden md:flex items-center gap-4">
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              홈
            </Link>
            <Link href="#" className="text-primary-foreground" prefetch={false}>
              시설
            </Link>
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              예약
            </Link>
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              사용자
            </Link>
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              공지사항
            </Link>
          </nav>
        </div>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" className="flex items-center gap-2">
              <Avatar className="w-8 h-8 border">
                <AvatarImage src="/placeholder-user.jpg" alt="관리자" />
                <AvatarFallback>AD</AvatarFallback>
              </Avatar>
              <span className="font-medium">관리자</span>
              <ChevronDownIcon className="w-4 h-4" />
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem>프로필</DropdownMenuItem>
            <DropdownMenuItem>설정</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>로그아웃</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </header> */}
      <main className="flex-1 bg-muted/40 py-8 px-6">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-2xl font-bold mb-6">시설 편집</h1>
          <form className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div className="grid gap-4">
              <div className="grid gap-2">
                <Label htmlFor="name">시설 이름</Label>
                <Input id="name" defaultValue="농구 코트" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="description">설명</Label>
                <Textarea id="description" rows={3} defaultValue="전문 장비를 갖춘 잘 관리된 농구 코트입니다." />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="location">위치</Label>
                <Input id="location" defaultValue="123 Main St, Anytown USA" />
              </div>
              <div className="grid gap-2">
                <Label htmlFor="price">가격</Label>
                <Input id="price" type="number" defaultValue="25" />
              </div>
            </div>
            <div className="grid gap-4">
              <div>
                <Label>시설 사진</Label>
                <div className="grid grid-cols-3 gap-4 mt-2">
                  <div className="relative group">
                    <img
                      src="/placeholder.svg"
                      width={120}
                      height={120}
                      alt="시설 사진"
                      className="aspect-square rounded-md object-cover"
                    />
                    <div className="absolute top-0 right-0 p-2 bg-background/80 rounded-bl-md group-hover:block flex items-center justify-between">
                      <Button variant="ghost" size="icon" className="text-muted-foreground">
                        <Trash2Icon className="w-4 h-4" />
                        <span className="sr-only">삭제</span>
                      </Button>
                    </div>
                  </div>
                  <div className="relative group">
                    <img
                      src="/placeholder.svg"
                      width={120}
                      height={120}
                      alt="시설 사진"
                      className="aspect-square rounded-md object-cover"
                    />
                    <div className="absolute top-0 right-0 p-2 bg-background/80 rounded-bl-md group-hover:block flex items-center justify-between">
                      <Button variant="ghost" size="icon" className="text-muted-foreground">
                        <Trash2Icon className="w-4 h-4" />
                        <span className="sr-only">삭제</span>
                      </Button>
                    </div>
                  </div>

                  <Button variant="ghost" size="icon" className="text-muted-foreground">
                    <PlusIcon className="w-6 h-6" />
                    <span className="sr-only">사진 추가</span>
                  </Button>
                </div>
              </div>
              <div>
                <Label>예약 설정</Label>
                <div className="grid gap-4 mt-2">
                  {/* <div className="grid gap-2">
                    <Label htmlFor="unavailable-dates">예약 불가능 날짜</Label>
                    <Popover>
                      <PopoverTrigger asChild>
                        <Button variant="outline" className="justify-between w-full">
                          <span>날짜 선택</span>
                          <ChevronDownIcon className="w-4 h-4" />
                        </Button>
                      </PopoverTrigger>
                      <PopoverContent className="p-0 max-w-[276px]">
                        <Calendar mode="range" />
                      </PopoverContent>
                    </Popover>
                  </div> */}
                  <div className="grid gap-2">
                    <Label htmlFor="available-hours">운영 시간</Label>
                    <div className="grid grid-cols-2 gap-4">
                      <Input id="available-hours-start" type="time" defaultValue="08:00" />
                      <Input id="available-hours-end" type="time" defaultValue="22:00" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </form>
          <div className="flex justify-end mt-8">
            <Button>변경 사항 저장</Button>
          </div>
        </div>
      </main>
      {/* <footer className="bg-primary text-primary-foreground py-6 px-6">
        <div className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="space-y-2">
            <h3 className="font-semibold">유니스포츠</h3>
            <p>
              유니스포츠는 고품질의 스포츠 시설과 서비스를 제공하는 선도적인 기업입니다. 우리는 지역 사회의 활동적이고
              건강한 생활 방식을 증진하는 데 전념하고 있습니다.
            </p>
          </div>
          <div className="space-y-2">
            <h3 className="font-semibold">문의하기</h3>
            <p>123 Main St, Anytown USA</p>
            <p>전화: (123) 456-7890</p>
            <p>이메일: info@unisport.com</p>
          </div>
          <div className="space-y-2">
            <h3 className="font-semibold">법적 정보</h3>
            <Link href="#" className="hover:underline" prefetch={false}>
              이용 약관
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              개인정보 보호 정책
            </Link>
            <div className="flex items-center gap-4">
              <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
                <FacebookIcon className="w-6 h-6" />
              </Link>
              <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
                <TwitterIcon className="w-6 h-6" />
              </Link>
              <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
                <InstagramIcon className="w-6 h-6" />
              </Link>
            </div>
          </div>
        </div>
      </footer> */}
    </div>
  )
}

function ChevronDownIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  )
}


function FacebookIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function Package2Icon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 9h18v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9Z" />
      <path d="m3 9 2.45-4.9A2 2 0 0 1 7.24 3h9.52a2 2 0 0 1 1.8 1.1L21 9" />
      <path d="M12 3v6" />
    </svg>
  )
}


function PlusIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function Trash2Icon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
      <line x1="10" x2="10" y1="11" y2="17" />
      <line x1="14" x2="14" y1="11" y2="17" />
    </svg>
  )
}


function TwitterIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
