/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/S6ON7Te3XrI
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rethink_Sans } from 'next/font/google'

rethink_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function AdminPage() {
  return (
    <div className="flex flex-col min-h-screen">
      <main className="flex-1">
        <section className="py-12 md:py-20">
          <div className="container px-4 md:px-6">
            <div className="max-w-3xl mx-auto space-y-8">
              <div className="space-y-4">
                <h1 className="text-3xl font-bold md:text-5xl">관리자 페이지</h1>
                <p className="text-muted-foreground text-lg md:text-xl">
                  시설, 예약, 사용자, 공지사항을 관리할 수 있습니다.
                </p>
              </div>
              <div className="grid gap-6">
              <Card>
                  <CardHeader>
                    <CardTitle>공지사항 관리</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid gap-4">
                      <Link href="/announcements-admin" className="flex items-center justify-between" prefetch={false}>
                        <div>공지사항 목록</div>
                        <ArrowRightIcon className="h-5 w-5" />
                      </Link>
                      <Link href="/announcement-write" className="flex items-center justify-between" prefetch={false}>
                        <div>새 공지사항 작성</div>
                        <ArrowRightIcon className="h-5 w-5" />
                      </Link>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle>시설 관리</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid gap-4">
                      <Link href="/src/components/admin/facility-admin" className="flex items-center justify-between" prefetch={false}>
                        <div>시설 목록</div>
                        <ArrowRightIcon className="h-5 w-5" />
                      </Link>
                      <Link href="/src/components/facility/facility-create" className="flex items-center justify-between" prefetch={false}>
                        <div>새 시설 등록</div>
                        <ArrowRightIcon className="h-5 w-5" />
                      </Link>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle>예약 관리</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid gap-4">
                      <Link href="/reservation-admin" className="flex items-center justify-between" prefetch={false}>
                        <div>예약 신청 목록</div>
                        <ArrowRightIcon className="h-5 w-5" />
                      </Link>
                    </div>
                  </CardContent>
                </Card>

                <Card>
                  <CardHeader>
                    <CardTitle>사용자 관리(서비스 예정...)</CardTitle>
                  </CardHeader>
                  <CardContent>
                    <div className="grid gap-4">
                      <Link href="#" className="flex items-center justify-between" prefetch={false}>
                        <div>사용자 목록</div>
                        <ArrowRightIcon className="h-5 w-5" />
                      </Link>
                      <Link href="#" className="flex items-center justify-between" prefetch={false}>
                        <div>사용자 등록</div>
                        <ArrowRightIcon className="h-5 w-5" />
                      </Link>
                      <Link href="#" className="flex items-center justify-between" prefetch={false}>
                        <div>사용자 정보 수정</div>
                        <ArrowRightIcon className="h-5 w-5" />
                      </Link>
                      <Link href="#" className="flex items-center justify-between" prefetch={false}>
                        <div>관리자 권한 부여</div>
                        <ArrowRightIcon className="h-5 w-5" />
                      </Link>
                    </div>
                  </CardContent>
                </Card>
              </div>
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}

function ArrowRightIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="m12 5 7 7-7 7" />
    </svg>
  )
}


function FilePenIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 22h6a2 2 0 0 0 2-2V7l-5-5H6a2 2 0 0 0-2 2v10" />
      <path d="M14 2v4a2 2 0 0 0 2 2h4" />
      <path d="M10.4 12.6a2 2 0 1 1 3 3L8 21l-4 1 1-4Z" />
    </svg>
  )
}


function MountainIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function TrashIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}
