/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/fQr0KQjDJVH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuItem, DropdownMenuSeparator } from "@/components/ui/dropdown-menu"
import { Button } from "@/components/ui/button"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"

export function AnnouncementWrite() {
  return (
    <div className="flex flex-col min-h-screen">
      {/* <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <LogInIcon className="h-6 w-6" />
          <span className="text-lg font-semibold">유니스포츠</span>
        </Link>
        <nav className="hidden md:flex items-center gap-6">
          <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
            홈
          </Link>
          <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
            시설 관리
          </Link>
          <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
            예약 관리
          </Link>
          <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
            사용자 관리
          </Link>
          <Link href="#" className="hover:text-primary-foreground/80 font-medium" prefetch={false}>
            공지 사항
          </Link>
        </nav>
        <DropdownMenu>
          <DropdownMenuTrigger asChild>
            <Button variant="ghost" size="icon" className="rounded-full">
              <Avatar className="w-8 h-8">
                <AvatarImage src="/placeholder-user.jpg" alt="관리자 아바타" />
                <AvatarFallback>AD</AvatarFallback>
              </Avatar>
            </Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent align="end">
            <DropdownMenuItem>프로필</DropdownMenuItem>
            <DropdownMenuItem>설정</DropdownMenuItem>
            <DropdownMenuSeparator />
            <DropdownMenuItem>로그아웃</DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </header> */}
      <main className="flex-1 py-8 px-6">
        <div className="max-w-3xl mx-auto">
          <h1 className="text-2xl font-bold mb-4">새 공지 사항 작성</h1>
          <form className="space-y-6">
            <div>
              <Label htmlFor="title">제목</Label>
              <Input id="title" placeholder="공지 사항 제목 입력" />
            </div>
            <div>
              <Label htmlFor="content">내용</Label>
              <Textarea id="content" rows={8} placeholder="공지 사항 내용 입력" className="min-h-[200px]" />
            </div>
            <Button type="submit" className="w-full">
              제출
            </Button>
          </form>
        </div>
      </main>
      
    </div>
  )
}




function LogInIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>
  )
}



