/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/8jPeeuvxrIZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Rubik } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function BookingList() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-semibold">유니스포츠</span>
        </Link>
        <nav className="hidden md:flex items-center gap-6">
          <Link href="#" className="hover:underline" prefetch={false}>
            홈
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            시설
          </Link>
          <Link href="#" className="hover:underline font-medium" prefetch={false}>
            예약
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            공지사항
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            계정
          </Link>
        </nav>
        <div className="flex items-center gap-4">
          <Link href="#" className="hover:underline" prefetch={false}>
            로그인
          </Link>
          <Avatar className="w-8 h-8 border">
            <AvatarImage src="/placeholder-user.jpg" alt="사용자 아바타" />
            <AvatarFallback>JD</AvatarFallback>
          </Avatar>
        </div>
      </header>
      <main className="flex-1 py-8 px-4 md:px-8">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-2xl font-bold mb-6">예약 내역</h1>
          <div className="space-y-4">
            <div className="bg-background rounded-lg shadow-md p-4">
              <div className="flex items-center justify-between mb-2">
                <div className="font-medium">농구장</div>
                <div className="text-sm text-muted-foreground">2023-05-01에 예약됨</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="text-sm text-muted-foreground">
                  예약 상태: <span className="font-medium text-green-500">확정</span>
                </div>
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm">
                    상세 보기
                  </Button>
                  <Button variant="outline" size="sm">
                    취소
                  </Button>
                </div>
              </div>
            </div>
            <div className="bg-background rounded-lg shadow-md p-4">
              <div className="flex items-center justify-between mb-2">
                <div className="font-medium">테니스장</div>
                <div className="text-sm text-muted-foreground">2023-04-15에 예약됨</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="text-sm text-muted-foreground">
                  예약 상태: <span className="font-medium text-yellow-500">대기 중</span>
                </div>
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm">
                    상세 보기
                  </Button>
                  <Button variant="outline" size="sm">
                    취소
                  </Button>
                </div>
              </div>
            </div>
            <div className="bg-background rounded-lg shadow-md p-4">
              <div className="flex items-center justify-between mb-2">
                <div className="font-medium">수영장</div>
                <div className="text-sm text-muted-foreground">2023-03-20에 예약됨</div>
              </div>
              <div className="flex items-center justify-between">
                <div className="text-sm text-muted-foreground">
                  예약 상태: <span className="font-medium text-red-500">취소됨</span>
                </div>
                <div className="flex items-center gap-2">
                  <Button variant="outline" size="sm">
                    상세 보기
                  </Button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
      <footer className="bg-muted text-muted-foreground py-6 px-4 md:px-8">
        <div className="max-w-4xl mx-auto flex flex-col md:flex-row items-center justify-between gap-4">
          <div className="text-sm">&copy; 2024 유니스포츠. 모든 권리 보유.</div>
          <nav className="flex items-center gap-4">
            <Link href="#" className="hover:underline" prefetch={false}>
              이용 약관
            </Link>
            <Link href="#" className="hover:underline" prefetch={false}>
              개인정보 정책
            </Link>
          </nav>
          <div className="flex items-center gap-4">
            <Link href="#" className="hover:text-primary" prefetch={false}>
              <FacebookIcon className="h-5 w-5" />
            </Link>
            <Link href="#" className="hover:text-primary" prefetch={false}>
              <TwitterIcon className="h-5 w-5" />
            </Link>
            <Link href="#" className="hover:text-primary" prefetch={false}>
              <InstagramIcon className="h-5 w-5" />
            </Link>
          </div>
        </div>
      </footer>
    </div>
  )
}

function FacebookIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function MountainIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function TwitterIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}
