/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/tGzDcWMO0kq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from "@/components/ui/select"
import { Card, CardContent } from "@/components/ui/card"
import { Badge } from "@/components/ui/badge"

export function FacilityList() {
  return (
    <div className="flex flex-col min-h-screen">
      {/* <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-bold">UniSport</span>
        </Link>
        <nav className="hidden md:flex items-center gap-6">
          <Link href="#" className="hover:underline" prefetch={false}>
            홈
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            시설
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            예약
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            공지사항
          </Link>
        </nav>
        <div className="flex items-center gap-4">
          <Button variant="ghost">
            <UserIcon className="h-5 w-5" />
            <span className="sr-only">프로필</span>
          </Button>
          <Button>로그인</Button>
        </div>
      </header> */}
      <main className="flex-1 py-8 px-4 md:px-8">
        <div className="max-w-6xl mx-auto">
          <div className="mb-8">
            <h1 className="text-3xl font-bold mb-2">시설 검색</h1>
            <p className="text-muted-foreground">원하는 시설을 찾아 예약하세요.</p>
          </div>
          <div className="bg-background rounded-lg border p-6 mb-8">
            <form className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
              <div>
                <Label htmlFor="search">검색</Label>
                <Input id="search" placeholder="시설 이름 검색" />
              </div>
              <div>
                <Label htmlFor="location">위치</Label>
                <Select>
                  <SelectTrigger id="location">
                    <SelectValue placeholder="위치 선택" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="campus-a">캠퍼스 A</SelectItem>
                    <SelectItem value="campus-b">캠퍼스 B</SelectItem>
                    <SelectItem value="campus-c">캠퍼스 C</SelectItem>
                  </SelectContent>
                </Select>
              </div>
              <div>
                <Label htmlFor="sport">종목</Label>
                <Select>
                  <SelectTrigger id="sport">
                    <SelectValue placeholder="종목 선택" />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="basketball">농구</SelectItem>
                    <SelectItem value="volleyball">배구</SelectItem>
                    <SelectItem value="soccer">축구</SelectItem>
                    <SelectItem value="tennis">테니스</SelectItem>
                  </SelectContent>
                </Select>
              </div>
            </form>
          </div>
          <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6">
            <Card>
              <Link href="/facility-resevations" prefetch={false}>
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={225}
                  alt="농구장"
                  className="rounded-t-lg object-cover"
                  style={{ aspectRatio: "400/225", objectFit: "cover" }}
                />
                <CardContent>
                  <h3 className="text-lg font-bold mb-2">농구장</h3>
                  <p className="text-muted-foreground mb-4">규격 농구장, 높이 조절 가능한 골대.</p>
                  <div className="flex items-center justify-between">
                    <Badge variant="default">
                      사용 가능
                    </Badge>
                    <Button variant="outline" size="sm">
                      자세히 보기
                    </Button>
                  </div>
                </CardContent>
              </Link>
            </Card>
            <Card>
              <Link href="#" prefetch={false}>
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={225}
                  alt="배구장"
                  className="rounded-t-lg object-cover"
                  style={{ aspectRatio: "400/225", objectFit: "cover" }}
                />
                <CardContent>
                  <h3 className="text-lg font-bold mb-2">배구장</h3>
                  <p className="text-muted-foreground mb-4">규격 배구장, 높이 조절 가능한 네트.</p>
                  <div className="flex items-center justify-between">
                    <Badge variant="default">
                      사용 가능
                    </Badge>
                    <Button variant="outline" size="sm">
                      자세히 보기
                    </Button>
                  </div>
                </CardContent>
              </Link>
            </Card>
            <Card>
              <Link href="#" prefetch={false}>
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={225}
                  alt="축구장"
                  className="rounded-t-lg object-cover"
                  style={{ aspectRatio: "400/225", objectFit: "cover" }}
                />
                <CardContent>
                  <h3 className="text-lg font-bold mb-2">축구장</h3>
                  <p className="text-muted-foreground mb-4">규격 축구장, 인조 잔디 표면.</p>
                  <div className="flex items-center justify-between">
                    <Badge variant="default">
                      사용 가능
                    </Badge>
                    <Button variant="outline" size="sm">
                      자세히 보기
                    </Button>
                  </div>
                </CardContent>
              </Link>
            </Card>
            <Card>
              <Link href="#" prefetch={false}>
                <img
                  src="/placeholder.svg"
                  width={400}
                  height={225}
                  alt="테니스장"
                  className="rounded-t-lg object-cover"
                  style={{ aspectRatio: "400/225", objectFit: "cover" }}
                />
                <CardContent>
                  <h3 className="text-lg font-bold mb-2">테니스장</h3>
                  <p className="text-muted-foreground mb-4">규격 테니스장, 하드 코트 표면.</p>
                  <div className="flex items-center justify-between">
                    <Badge variant="default">
                      사용 가능
                    </Badge>
                    <Button variant="outline" size="sm">
                      자세히 보기
                    </Button>
                  </div>
                </CardContent>
              </Link>
            </Card>
          </div>
        </div>
      </main>

      {/* <footer className="bg-muted text-muted-foreground py-6 px-4 md:px-8">
        <div className="max-w-6xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          <div>
            <h3 className="text-lg font-bold mb-4">UniSport 소개</h3>
            <p className="text-sm">
              UniSport는 대학 내 다양한 스포츠 시설을 손쉽게 예약할 수 있는 웹 애플리케이션입니다.
            </p>
          </div>
          <div>
            <h3 className="text-lg font-bold mb-4">문의</h3>
            <p className="text-sm">
              전화: 123-456-7890
              <br />
              이메일: info@unisport.com
            </p>
          </div>
          <div>
            <h3 className="text-lg font-bold mb-4">법적 정보</h3>
            <ul className="space-y-2 text-sm">
              <li>
                <Link href="#" className="hover:underline" prefetch={false}>
                  이용 약관
                </Link>
              </li>
              <li>
                <Link href="#" className="hover:underline" prefetch={false}>
                  개인정보 보호 정책
                </Link>
              </li>
            </ul>
          </div>
        </div>
        <div className="max-w-6xl mx-auto mt-8 flex justify-between items-center">
          <p className="text-sm text-muted-foreground/80">&copy; 2024 UniSport. All rights reserved.</p>
          <div className="flex items-center gap-4">
            <Link href="#" className="hover:text-primary-foreground" prefetch={false}>
              <TwitterIcon className="h-5 w-5" />
            </Link>
            <Link href="#" className="hover:text-primary-foreground" prefetch={false}>
              <FacebookIcon className="h-5 w-5" />
            </Link>
            <Link href="#" className="hover:text-primary-foreground" prefetch={false}>
              <InstagramIcon className="h-5 w-5" />
            </Link>
          </div>
        </div>
      </footer> */}
    </div>
  )
}

function FacebookIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function MountainIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function TwitterIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function UserIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
