/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/q5CuUOvm1AK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { Arimo } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function Homepage() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 flex items-center justify-between">
        <Link href="#" className="flex items-center gap-2" prefetch={false}>
          <MountainIcon className="h-6 w-6" />
          <span className="text-lg font-bold">UniSport</span>
        </Link>
        <nav className="hidden md:flex items-center gap-6">
          <Link href="#" className="hover:underline" prefetch={false}>
            홈
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            시설
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            예약
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            공지사항
          </Link>
        </nav>
        <div className="flex items-center gap-4">
          <Link href="#" className="hover:underline" prefetch={false}>
            로그인
          </Link>
          <Link
            href="#"
            className="bg-primary-foreground text-primary px-4 py-2 rounded-md hover:bg-primary/90"
            prefetch={false}
          >
            회원가입
          </Link>
        </div>
      </header>
      <main className="flex-1 py-12 px-6">
        <section className="max-w-5xl mx-auto space-y-8">
          <div>
            <h1 className="text-4xl font-bold">UniSport에 오신 것을 환영합니다!</h1>
            <p className="text-muted-foreground text-lg">대학교 내 최고의 스포츠 시설을 찾아보고 예약하세요.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div className="bg-muted rounded-lg p-6 space-y-4">
              <CalendarIcon className="h-8 w-8 text-primary" />
              <h3 className="text-xl font-bold">시설 예약하기</h3>
              <p className="text-muted-foreground">편리하게 스포츠 시설을 검색하고 예약하세요.</p>
              <Link href="#" className="text-primary hover:underline" prefetch={false}>
                시설 보기
              </Link>
            </div>
            <div className="bg-muted rounded-lg p-6 space-y-4">
              <BellIcon className="h-8 w-8 text-primary" />
              <h3 className="text-xl font-bold">최신 소식 확인하기</h3>
              <p className="text-muted-foreground">UniSport의 최신 공지사항과 뉴스를 확인하세요.</p>
              <Link href="#" className="text-primary hover:underline" prefetch={false}>
                공지사항 보기
              </Link>
            </div>
            <div className="bg-muted rounded-lg p-6 space-y-4">
              <UserIcon className="h-8 w-8 text-primary" />
              <h3 className="text-xl font-bold">예약 관리하기</h3>
              <p className="text-muted-foreground">지난 예약 내역과 예정된 예약을 확인하세요.</p>
              <Link href="#" className="text-primary hover:underline" prefetch={false}>
                예약 내역 보기
              </Link>
            </div>
          </div>
          <div>
            <h2 className="text-2xl font-bold mb-4">최신 공지사항</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-muted rounded-lg p-4 space-y-2">
                <h3 className="text-lg font-bold">새로운 체육관 장비 설치</h3>
                <p className="text-muted-foreground">최신 장비를 추가로 설치했습니다. 확인해보세요!</p>
                <Link href="#" className="text-primary hover:underline" prefetch={false}>
                  자세히 보기
                </Link>
              </div>
              <div className="bg-muted rounded-lg p-4 space-y-2">
                <h3 className="text-lg font-bold">수영장 정기 점검 안내</h3>
                <p className="text-muted-foreground">
                  수영장은 6월 1일부터 15일까지 정기 점검으로 이용이 불가능합니다.
                </p>
                <Link href="#" className="text-primary hover:underline" prefetch={false}>
                  자세히 보기
                </Link>
              </div>
              <div className="bg-muted rounded-lg p-4 space-y-2">
                <h3 className="text-lg font-bold">새로운 배드민턴 코트 오픈</h3>
                <p className="text-muted-foreground">2개의 새로운 배드민턴 코트가 오픈했습니다. 지금 예약하세요!</p>
                <Link href="#" className="text-primary hover:underline" prefetch={false}>
                  자세히 보기
                </Link>
              </div>
            </div>
          </div>
          <div>
            <h2 className="text-2xl font-bold mb-4">인기 시설</h2>
            <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
              <div className="bg-muted rounded-lg p-4 space-y-2">
                <img
                  src="/placeholder.svg"
                  alt="체육관"
                  className="rounded-lg object-cover aspect-video"
                  width="300"
                  height="200"
                />
                <h3 className="text-lg font-bold">체육관</h3>
                <p className="text-muted-foreground">최신 장비를 갖춘 우리 체육관에서 운동하세요.</p>
                <Link href="#" className="text-primary hover:underline" prefetch={false}>
                  시설 보기
                </Link>
              </div>
              <div className="bg-muted rounded-lg p-4 space-y-2">
                <img
                  src="/placeholder.svg"
                  alt="수영장"
                  className="rounded-lg object-cover aspect-video"
                  width="300"
                  height="200"
                />
                <h3 className="text-lg font-bold">수영장</h3>
                <p className="text-muted-foreground">올림픽 규격의 수영장에서 여유롭게 수영하세요.</p>
                <Link href="#" className="text-primary hover:underline" prefetch={false}>
                  시설 보기
                </Link>
              </div>
              <div className="bg-muted rounded-lg p-4 space-y-2">
                <img
                  src="/placeholder.svg"
                  alt="테니스 코트"
                  className="rounded-lg object-cover aspect-video"
                  width="300"
                  height="200"
                />
                <h3 className="text-lg font-bold">테니스 코트</h3>
                <p className="text-muted-foreground">잘 관리된 테니스 코트에서 즐겁게 테니스를 치세요.</p>
                <Link href="#" className="text-primary hover:underline" prefetch={false}>
                  시설 보기
                </Link>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted text-muted-foreground py-8 px-6">
        <div className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="space-y-4">
            <h3 className="text-lg font-bold">UniSport 소개</h3>
            <p>UniSport는 대학생들이 캠퍼스 내 스포츠 시설을 쉽게 예약하고 관리할 수 있는 웹 애플리케이션입니다.</p>
            <p>
              문의사항은{" "}
              <a href="#" className="text-primary hover:underline">
                info@unisport.com
              </a>
              으로 보내주세요.
            </p>
          </div>
          <div className="space-y-4">
            <h3 className="text-lg font-bold">빠른 링크</h3>
            <ul className="space-y-2">
              <li>
                <Link href="#" className="text-primary hover:underline" prefetch={false}>
                  이용 약관
                </Link>
              </li>
              <li>
                <Link href="#" className="text-primary hover:underline" prefetch={false}>
                  개인정보 보호 정책
                </Link>
              </li>
            </ul>
          </div>
          <div className="space-y-4">
            <h3 className="text-lg font-bold">팔로우하기</h3>
            <div className="flex items-center gap-4">
              <Link href="#" className="text-primary hover:underline" prefetch={false}>
                <TwitterIcon className="h-6 w-6" />
              </Link>
              <Link href="#" className="text-primary hover:underline" prefetch={false}>
                <FacebookIcon className="h-6 w-6" />
              </Link>
              <Link href="#" className="text-primary hover:underline" prefetch={false}>
                <InstagramIcon className="h-6 w-6" />
              </Link>
            </div>
          </div>
        </div>
      </footer>
    </div>
  )
}

function BellIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M6 8a6 6 0 0 1 12 0c0 7 3 9 3 9H3s3-2 3-9" />
      <path d="M10.3 21a1.94 1.94 0 0 0 3.4 0" />
    </svg>
  )
}


function CalendarIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  )
}


function FacebookIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z" />
    </svg>
  )
}


function InstagramIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>
  )
}


function MountainIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  )
}


function TwitterIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>
  )
}


function UserIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
